### ISSUE TITLE
Downloading the pretrained model

### ISSUE THREAD

**Issue by pjy0422** [hustvl/circuitformer#4]
Hi. I want to download the pretrained model, but I can't because the link is baidu netdisk. I'm Korean, and baidu netdisk doesn't seem to allow foreigners to sign up, so could you please provide another option for the download link of pretrained model, such as google drive?

**Comment by Doctor-James** [comment]
Of course, please download the pretrain model in [Google](https://drive.google.com/file/d/1IyYG2uQMvnZ6C4O0e0FFEfIHRlJXrV24/view?usp=sharing), and readme has been updated
