### ISSUE TITLE
label

### ISSUE THREAD

**Issue by guofeng97** [hustvl/circuitformer#5]
想请问一下，为什么在训练的时候，是将坐标和label输入到模型当中，而不是feature，这样不是数据泄露了吗

**Comment by Doctor-James** [comment]
什么叫输入label，是指Label Distribution Smoothing部分吗，这部分只是统计了训练集的数据分布，然后做loss的重加权，这个模块只会在训练中使用，测试时不会使用，具体可以看看[Delving into deep imbalanced regression](https://arxiv.org/abs/2102.09554)

**Comment by guofeng97** [comment]
哦哦好的谢谢！
